type SquareBracketClassesMap = {
  [key: string]: string;
};

export const squareBracketClassesMap: SquareBracketClassesMap = {
  'opacity': 'opacity:',
  'fill': 'fill:',
  'text': 'color:',
  'bg': 'background-color:',
  'pr': 'padding-right:',
  'pl': 'padding-left:',
  'pb': 'padding-bottom:',
  'pt': 'padding-top:',
  'p': 'padding:',
  'mr': 'margin-right:',
  'ml': 'margin-left:',
  'mb': 'margin-bottom:',
  'mt': 'margin-top:',
  'm': 'margin:',
  'top': 'top:',
  'left': 'left:',
  'right': 'right:',
  'bottom': 'bottom:',
  'h': 'height:',
  'w': 'width:',
  'border': 'border-width:',
  'min-h': 'min-height:',
  'max-h': 'max-height:',
  'min-w': 'min-width:',
  'max-w': 'max-width:',
  'gap-x': 'column-gap:',
  'gap-y': 'row-gap:',
  'gap': 'gap:',
  'outline': 'outline-width:',
  'accent': 'accent-color:',
  'caret': 'caret-color:',
  'stroke': 'stroke-color:',
  'decoration': 'text-decoration-color:',
  'indent': 'text-indent:',
  'leading': 'line-height:', 
  'z': 'z-index:',
  'columns': 'columns:'
};